# Generated by Django 4.2.5 on 2023-09-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='nombre_region',
        ),
        migrations.RenameField(
            model_name='region_pokemon',
            old_name='pokemon',
            new_name='id_pokemon',
        ),
        migrations.RenameField(
            model_name='region_pokemon',
            old_name='region',
            new_name='id_region',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='tipo',
            new_name='nombre_tipo',
        ),
    ]
