# Generated by Django 4.2.5 on 2023-09-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0002_rename_region_region_nombre_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_pokemon',
            old_name='pokemon',
            new_name='id_pokemon',
        ),
        migrations.RenameField(
            model_name='tipo_pokemon',
            old_name='tipo',
            new_name='id_tipo',
        ),
    ]
